### ISSUE TITLE
Cannot sync pointer with own origin

### ISSUE THREAD

**Issue by jonasstrehle** [unyt-org/datex-core-js-legacy#54]
Discovered this bug in https://github.com/unyt-org/homepage/tree/upgrade-uix.
Occured 10+ times on restart of container and initial website visit.

```ts
UIX Server  invalid session for @@44FD6AA70E000000006043743FA7BDC2/0001 (6dbf94ea6d6052205c911a7038ba5127882020252621a657cd75c8)
  DATEX  subscribing to $D1756E79745F686D706732x902574EC00300, origin: @+unyt_hmpg2/0002
⭢  (@+unyt_hmpg2/0002) ─────────────────────────────────
yeet <PointerError> [
   "Cannot sync pointer with own origin",
   [
      [
         #sub_result = var a = @+unyt_hmpg2/0002,
         "JavaScript Error at async send (https://cdn.unyt.org/datex-core-js-legacy@0.0.x/network/client.ts:796:13)"
         ],
      [
         a,
         "JavaScript Error at async Function.handleDatexIn (https://cdn.unyt.org/datex-core-js-legacy@0.0.x/runtime/runtime.ts:1980:21)"
         ],
      [
         a,
         "JavaScript Error at eventLoopTick (ext:core/01_core.js:183:11)"
         ],
      [
         a,
         "JavaScript Error at Function.run (https://cdn.unyt.org/datex-core-js-legacy@0.0.x/runtime/runtime.ts:6871:48)"
         ],
      [
         a,
         "JavaScript Error at Object.insertToScope (https://cdn.unyt.org/datex-core-js-legacy@0.0.x/runtime/runtime.ts:4562:29)"
         ],
      [
         a,
         "JavaScript Error at DecimalRef.addSubscriber (https://cdn.unyt.org/datex-core-js-legacy@0.0.x/runtime/pointers.ts:2982:19)"
         ]
      ]
   ];
─────────────────────────────────────────────────────────
⭠  @+unyt_hmpg2/0002 ────────────────────────────────────
yeet <PointerError> [
   "Cannot sync pointer with own origin",
   [
      [
         #sub_result = var a = @+unyt_hmpg2/0002,
         "JavaScript Error at async send (https://cdn.unyt.org/datex-core-js-legacy@0.0.x/network/client.ts:796:13)"
         ],
      [
         a,
         "JavaScript Error at async Function.handleDatexIn (https://cdn.unyt.org/datex-core-js-legacy@0.0.x/runtime/runtime.ts:1980:21)"
         ],
      [
         a,
         "JavaScript Error at eventLoopTick (ext:core/01_core.js:183:11)"
         ],
      [
         a,
         "JavaScript Error at Function.run (https://cdn.unyt.org/datex-core-js-legacy@0.0.x/runtime/runtime.ts:6871:48)"
         ],
      [
         a,
         "JavaScript Error at Object.insertToScope (https://cdn.unyt.org/datex-core-js-legacy@0.0.x/runtime/runtime.ts:4562:29)"
         ],
      [
         a,
         "JavaScript Error at DecimalRef.addSubscriber (https://cdn.unyt.org/datex-core-js-legacy@0.0.x/runtime/pointers.ts:2982:19)"
         ]
      ]
   ];
─────────────────────────────────────────────────────────
transpiler  removing cache directory: file:///tmp/transpiler_cache_8051d7bd/
error: Uncaught (in promise) PointerError: Cannot sync pointer with own origin
                    else if(old_value instanceof Array) new_value = new PointerError(old_value[0], old_value[1])
```

**Comment by benStre** [comment]
This happens because the eternal pointer was created before the endpoint instance was added, leading to a pointer origin without an instance. This pointer can be loaded from the storage, but the instance endpoint tries to subscribe at the non-instance endpoint, which it considers a remote endpoint because it does not equal the current instance.
But during routing, the DATEX message is sent back to the current endpoint, leading to the error.

**Comment by benStre** [comment]
Fixed for now in https://github.com/unyt-org/datex-core-js-legacy/pull/56
Subsequent issue: https://github.com/unyt-org/datex-core-js-legacy/issues/55

**Comment by benStre** [comment]
(In the case of the homepage, the malicious pointer was the statistics counter)
